[app]
log_level = "debug" # `debug` for verbose logs. `info` otherwise.
env = "dev" # dev|prod.
refresh_interval = "10s" # Interval at which list of allocations is updated.
remove_alloc_interval = "30s" # If the alloc is completed or stopped, the allocation isn't removed immediately from vector's config. You can delay the removal of alloc by `n` duration to ensure that vector has finished collecting all logs till then.
nomad_data_dir = "/opt/nomad/data/alloc" # Nomad data directory where alloc logs are stored.
custom_logs_dir = "" # for Java log4j  - "alloc/log4j/*.log"
vector_config_dir = "examples/vector/" # Path to the generated vector config file.
extra_templates_dir = "static/" # Extra templates that can be given. They will be rendered in directory mentioned by `vector_config_dir`. You can use variables mentioned in vector.toml.tmpl if required.
